### ISSUE TITLE
OfflineKey

### ISSUE THREAD

**Issue by minglee** [mtvg/August#1]
I followed your instructions but don't see any entry for AGCurrentUserOfflineKey in the latest version of the app.  Did the name of the entry change?

Open the file com.august.iossapp/Library/Preferences/com.august.iossapp.plist using Xcode or any binary plist viewer
Look inside Root/AGCurrentUserOfflineKey_XXXXXXXXXXXXXX

**Comment by mtvg** [comment]
I've just tested on a blank iPod I had, installed the app, logged in, and extracted the preferences, this is what I have:
![offlinekey](https://cloud.githubusercontent.com/assets/2505812/12011852/cc4133e6-ac94-11e5-883e-f15b9fea84fc.png)

Any chances on your side?

**Comment by minglee** [comment]
What version of the August iOS app are you running?  I'm at 3.2.14 and I only see 35 items under Root.  Looks like you have 45 items.

**Comment by mtvg** [comment]
3.2.14 as well. 
Do you know which version of the lock you have? There is a new version with HomeKit enabled, I am wondering if there is a difference in that one, I had mine for more than a year. 
Or maybe a specific feature of the lock creates that offline key, like the AutoUnlock feature perhaps?
FYI, my firmware version is 7aac73dd-1.0.80.1.1.18

**Comment by minglee** [comment]
That worked!  Looks like either AutoUnlock or Everlock needed to be turned on for the OfflineKey to be generated.  Thanks for your help!

**Comment by mtvg** [comment]
Excellent! I'll add a note to the instructions.
